server:
  port: 5050
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Springtest
    username: root
    password: Milano2024!
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false
